### ISSUE TITLE
rDock

### ISSUE THREAD

**Issue by sweetkurapika** [tsudalab/ChemGE#1]
I followed your instruction for installing the required dependencies.
I installed rDock, but when I run the following command:

$ python -u optimize-rdock-qsub.py

I got the following error:

/bin/sh: 1: qsub: not found

How can we fix it?

**Comment by n-yoshikawa** [comment]
In order to execute `optimize-rdock-qsub.py`, you need to install qsub on your machine.
The instruction to install qsub is missing in the document. I'm sorry for that.
I used [CfnCluster](https://github.com/awslabs/cfncluster), which has qsub by default.

Could you install qsub by yourself, or try `optimize-J.py` or `optimize-rdock.py` instead?

**Comment by sweetkurapika** [comment]
Thanks for swift replying.

I tried those, no problem.
optimize-rdock-qsub.py is only for computing clusters? 
If so, then I can only rely on optimize-J.py or optimize-rdock.py. Correct?

I appreciate your help

**Comment by n-yoshikawa** [comment]
Yes. `optimize-rdock-qsub.py` optimizes the same target as `optimize-rdock.py`. The difference is that qsub version is for cluster environment and the other is not.
