### ISSUE TITLE
Error installing rDock

### ISSUE THREAD

**Issue by NamanChuriwala** [tsudalab/ChemGE#7]
Hi,
I'm trying to install rDock in the way you have described. 
After running the command, **tar xf rDock_2013.1_src.tar.gz**, I get the following error:
**tar: Exiting with failure status due to previous errors**

I've tried installing rDock in 3 instances now but it doesn't work in any of them. Can you help me this?
Thanks!

**Comment by n-yoshikawa** [comment]
That error seems to be a problem of tar command, so I'm not familiar with it.

Google told me that such error tend to occur when the permission of files is not appropriate. Please check settings of permission again. If it is not solved, please show me full error message, since I can't tell what is "previous errors" from your post.

**Comment by NamanChuriwala** [comment]
I solved the error by simply adding 'sudo' before the command. It was a permission error.
